#created on: Dec 15, 2018
package com.sample

import com.sample.userChoice
import Model.UserModel
import Controller.UserFrame;
import Controller.UserFrame.Answers;


//declare any global variables here
dialect "java"

rule "Selective Mutism"
   
   when
      $a : Answers (answers contains "Yes" && (contains "Education" || contains "Occupation"));
   then
      System.out.println($a);
      System.out.println("TESTING");
    	//$a.updateIdx();
        //update( $a );
end
